### PR TITLE
Feature/domains onduty w33 2024

### PR DESCRIPTION
**Pull request by tbnc**
Adding several domains corresponding to runs performed by DEODE Triggering on-duty team during week 33-2024.

### CODE REVIEW

**Comment by tbnc** [comment]
Do we need to transfer the data to ec from ectmp @uandrae?

**Comment by tbnc** [comment]
We might also need some different directory structure/naming for folders.

**Comment by uandrae** [comment]
> Do we need to transfer the data to ec from ectmp @uandrae?

Yes, for the data not to be lost it needs to be transferred.

**Comment by uandrae** [comment]
> We might also need some different directory structure/naming for folders.

I'm happy to leave to @observingClouds to think about this.

**Review by uandrae — APPROVED** [review]
LGTM! Sorry about the slow response. For the location of the data (ec vs ectmp) I'd suggest to merge this and deal with the update once the data is in place.

**Comment by observingClouds** [comment]
> > We might also need some different directory structure/naming for folders.
> 
> I'm happy to leave to @observingClouds to think about this.

Yes, the naming needs some thinking as this PR adds now also a "reason" for the simulations. The filenames should probably do not contain any specific information about the simulation, but for now this is ok.

**Pull request merged**
